import { 
  Code2, 
  Palette, 
  FileText, 
  Bot, 
  Wrench, 
  Package 
} from 'lucide-react';
import { Theme } from './types';

export const themes: Theme[] = [
  {
    id: 'classic',
    name: 'Classic Dark',
    dark: {
      bg: '#0D0D0D',
      card: '#181818',
      border: '#2A2A2A',
      primary: '#6366F1',
      text: '#FAFAFA',
      muted: '#A1A1AA',
      accent: '#22C55E',
    },
    light: {
      bg: '#FFFFFF',
      card: '#F5F5F5',
      border: '#E5E5E5',
      primary: '#6366F1',
      text: '#0D0D0D',
      muted: '#71717A',
      accent: '#22C55E',
    },
  },
  {
    id: 'midnight',
    name: 'Midnight Blue',
    dark: {
      bg: '#0F172A',
      card: '#1E293B',
      border: '#334155',
      primary: '#3B82F6',
      text: '#F8FAFC',
      muted: '#94A3B8',
      accent: '#F59E0B',
    },
    light: {
      bg: '#F8FAFC',
      card: '#FFFFFF',
      border: '#E2E8F0',
      primary: '#3B82F6',
      text: '#0F172A',
      muted: '#64748B',
      accent: '#F59E0B',
    },
  },
  {
    id: 'forest',
    name: 'Forest Dark',
    dark: {
      bg: '#0A0F0A',
      card: '#1A2E1A',
      border: '#2D4A2D',
      primary: '#10B981',
      text: '#ECFDF5',
      muted: '#6EE7B7',
      accent: '#FCD34D',
    },
    light: {
      bg: '#F0FDF4',
      card: '#FFFFFF',
      border: '#D1FAE5',
      primary: '#10B981',
      text: '#0A0F0A',
      muted: '#6EE7B7',
      accent: '#FCD34D',
    },
  },
  {
    id: 'violet',
    name: 'Violet Dark',
    dark: {
      bg: '#0D0B1E',
      card: '#1A1630',
      border: '#2E2650',
      primary: '#A855F7',
      text: '#FAF5FF',
      muted: '#D8B4FE',
      accent: '#F472B6',
    },
    light: {
      bg: '#FAF5FF',
      card: '#FFFFFF',
      border: '#E9D5FF',
      primary: '#A855F7',
      text: '#0D0B1E',
      muted: '#C084FC',
      accent: '#F472B6',
    },
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    dark: {
      bg: '#0A0A0F',
      card: '#151520',
      border: '#2A2A40',
      primary: '#FF0080',
      text: '#FAFAFA',
      muted: '#A0A0B0',
      accent: '#00FFFF',
    },
    light: {
      bg: '#FAFAFA',
      card: '#F0F0F5',
      border: '#E0E0F0',
      primary: '#FF0080',
      text: '#0A0A0F',
      muted: '#707080',
      accent: '#0088FF',
    },
  },
  {
    id: 'sunset',
    name: 'Sunset',
    dark: {
      bg: '#1A0A0A',
      card: '#2A1515',
      border: '#4A2525',
      primary: '#FF6B35',
      text: '#FFF5F0',
      muted: '#FFB59A',
      accent: '#FFD700',
    },
    light: {
      bg: '#FFF8F5',
      card: '#FFFFFF',
      border: '#FFE4D6',
      primary: '#FF6B35',
      text: '#1A0A0A',
      muted: '#CC5530',
      accent: '#FF8C00',
    },
  },
  {
    id: 'ocean',
    name: 'Ocean',
    dark: {
      bg: '#0A1628',
      card: '#122040',
      border: '#1E3A5F',
      primary: '#06B6D4',
      text: '#F0F9FF',
      muted: '#7DD3FC',
      accent: '#34D399',
    },
    light: {
      bg: '#F0F9FF',
      card: '#FFFFFF',
      border: '#BAE6FD',
      primary: '#0284C7',
      text: '#0A1628',
      muted: '#0EA5E9',
      accent: '#059669',
    },
  },
  {
    id: 'rose',
    name: 'Rose Gold',
    dark: {
      bg: '#1A0F14',
      card: '#2A1820',
      border: '#3D2830',
      primary: '#F472B6',
      text: '#FFF5F8',
      muted: '#FDA4AF',
      accent: '#FBBF24',
    },
    light: {
      bg: '#FDF2F8',
      card: '#FFFFFF',
      border: '#FECDD3',
      primary: '#EC4899',
      text: '#1A0F14',
      muted: '#F472B6',
      accent: '#D97706',
    },
  },
  {
    id: 'nord',
    name: 'Nord',
    dark: {
      bg: '#2E3440',
      card: '#3B4252',
      border: '#4C566A',
      primary: '#81A1C1',
      text: '#ECEFF4',
      muted: '#D8DEE9',
      accent: '#A3BE8C',
    },
    light: {
      bg: '#ECEFF4',
      card: '#E5E9F0',
      border: '#D8DEE9',
      primary: '#5E81AC',
      text: '#2E3440',
      muted: '#4C566A',
      accent: '#A3BE8C',
    },
  },
  {
    id: 'dracula',
    name: 'Dracula',
    dark: {
      bg: '#282A36',
      card: '#383A59',
      border: '#44475A',
      primary: '#BD93F9',
      text: '#F8F8F2',
      muted: '#6272A4',
      accent: '#50FA7B',
    },
    light: {
      bg: '#FAFAFA',
      card: '#F8F8F2',
      border: '#44475A',
      primary: '#BD93F9',
      text: '#282A36',
      muted: '#6272A4',
      accent: '#50FA7B',
    },
  },
  {
    id: 'gruvbox',
    name: 'Gruvbox',
    dark: {
      bg: '#282828',
      card: '#3C3836',
      border: '#504945',
      primary: '#FABC2C',
      text: '#FBF1C7',
      muted: '#D79921',
      accent: '#83C07C',
    },
    light: {
      bg: '#FBF1C7',
      card: '#F2EBC8',
      border: '#D5C4A1',
      primary: '#C35E00',
      text: '#282828',
      muted: '#9D6E00',
      accent: '#427B58',
    },
  },
  {
    id: 'monokai',
    name: 'Monokai',
    dark: {
      bg: '#272822',
      card: '#3E3D32',
      border: '#49483E',
      primary: '#F92672',
      text: '#F8F8F2',
      muted: '#AE81FF',
      accent: '#A6E22E',
    },
    light: {
      bg: '#FAFAFA',
      card: '#F8F8F2',
      border: '#49483E',
      primary: '#F92672',
      text: '#272822',
      muted: '#AE81FF',
      accent: '#A6E22E',
    },
  },
  {
    id: 'solarized',
    name: 'Solarized',
    dark: {
      bg: '#002B36',
      card: '#073642',
      border: '#094550',
      primary: '#268BD2',
      text: '#FDF6E3',
      muted: '#93A1A1',
      accent: '#859900',
    },
    light: {
      bg: '#FDF6E3',
      card: '#EEE8D5',
      border: '#D6C7A1',
      primary: '#268BD2',
      text: '#002B36',
      muted: '#586E75',
      accent: '#859900',
    },
  },
];

// Lucide icon components for categories
export const categoryIcons = {
  dev: Code2,
  design: Palette,
  docs: FileText,
  ai: Bot,
  util: Wrench,
  other: Package,
};

export const categories = [
  { id: 'dev', name: 'Development', icon: Code2 },
  { id: 'design', name: 'Design', icon: Palette },
  { id: 'docs', name: 'Documentation', icon: FileText },
  { id: 'ai', name: 'AI/ML', icon: Bot },
  { id: 'util', name: 'Utilities', icon: Wrench },
  { id: 'other', name: 'Other', icon: Package },
];
